### PR TITLE
Add support for Zend Framework 3

### PR DESCRIPTION
**Pull request by alfaproject**

### CODE REVIEW

**Comment by markushausammann** [comment]
Thanks, proved and tested and that's all that's needed to make it ZF3 compatible? Does it mean a BC break?

**Comment by alfaproject** [comment]
The console stuff is deprecated, so I didn't test that. Zend Http should be fine, but I'm still testing this. Our QA will be testing today/tomorrow.

I'll get back to you regarding the results, and I'll have a look at the console stuff as well if you want.

**Comment by markushausammann** [comment]
That would be awesome, thanks!

**Comment by alfaproject** [comment]
I can confirm that at least for my APIs everything was QAed and is already on production. (;
We should probably have some tests, but I honestly don't have time right now to work on them.

Maybe I'll contribute a bit more over the coming weeks/months.

**Comment by markushausammann** [comment]
All right, thanks for the help and info! I'm going to tag a new release today.

**Comment by markushausammann** [comment]
Ok, so this actually introduces a BC break for ZF2... I'll need to decide which one to keep in the master branch.

**Comment by alfaproject** [comment]
Yes indeed. ):

**Comment by markushausammann** [comment]
This pull request is now merged with the `zf3-compat` branch and I tagge a `3.0.0` release from that branch. Please test. There is another pull request for ZF3 compatibility so I'll soon tag `3.0.1` already.

**Pull request merged**
